### ISSUE TITLE
Update swagger version

### ISSUE THREAD

**Issue by sburnicki** [ajay-kmr/swagger#12]
Hey,
could you update the swagger version, e.g. to 1.5.20 and re-release this plugin?

In 1.5.17 they resolved the issue with the `logback-test.xml`, see
https://github.com/swagger-api/swagger-core/releases/tag/v1.5.17

(It took me some hours to find out why my logs disappeared, so I'd like to save this effort for others).

**Comment by vamsi-emani** [comment]
Can you please update the swagger version? The logback logging issue has been fixed long back by swagger and there were newer versions of swagger-servlet released post that. This plugin is still using an old version. Is there a plan to support this plugin with future releases of swagger?

**Comment by ajay-kmr** [comment]
The swagger version has been updated to 1.5.22 and swagger UI version has been updated to 3.20.9 in release 1.0.1.
