### ISSUE TITLE
swagger-ui version (2.2.5) is hardcoded, but should be configurable

### ISSUE THREAD

**Issue by prokhor-ozornin** [ajay-kmr/swagger#2]
Version of used swagger-ui library is hardcoded in ApiDocController: 
`redirect uri: "/webjars/swagger-ui/2.2.5/index.html?url=${request.getRequestURI()}"`

Users should be able to add their own version of swagger-ui library in build.gradle and use it instead of 'default' version, provided with a plugin. I suggest moving swagger-ui library version in configuration file (application.yaml/application.groovy).

**Comment by ajay-kmr** [comment]
Hi Prokhor Ozornin,

Thanks for your feedback.

The swagger-ui library with version 2.2.5 is the most compatible version with the other swagger's dependency (eg swagger-core) used in this plugin. So this version of swagger-ui is used intentionally to avoid any dependency conflict.

Making the swagger-ui library version configurable may add extra complexity/responsibility to the user of the plugin and it may sometimes lead to bad experience for the user in case of dependency conflict.

However as per your suggestion, I will try to provide both the options- 1) Use default version 2) Make the version configurable.

I will try to incorporate this changes in upcoming releases based on it's priority.

**Comment by cfsilence** [comment]
Any update on this ticket?  I'd really like to get up to Swagger 3.0 to get the fix for https://github.com/swagger-api/swagger-ui/issues/1248 into my Grails application.

**Comment by ajay-kmr** [comment]
This issue is taken on priority and is planned to be released before Jul 22  UTC 2017

**Comment by cfsilence** [comment]
Meanwhile, i've dropped in the jar for swagger-ui 3.0.19 and the new UI works for me.

**Comment by ajay-kmr** [comment]
The issue has been fixed in version in version- 1.0.0. 
Users can add their own version of swagger-ui library in build.gradle

The updated dependency information of this fix is:- 

repositories {
    maven { url "https://dl.bintray.com/ajay-kumar/plugins" }
}

dependencies {
    compile 'org.grails.plugins:swagger:1.0.0'
}

**Comment by ajay-kmr** [comment]
Issue resolved in version> 1.0.0
