### ISSUE TITLE
ImplicitParams are not being retrieved

### ISSUE THREAD

**Issue by aspich** [ajay-kmr/swagger#3]
Hello,

Thanks for provinding this great plugin. However I have done the setup as stated, all the responses and api params are properly described with exception of the Request Params. I have tried different types and combinations, but they seem to be ignored by the service.

Could you please review this code part?

Thanks,
Andrio

**Comment by miguelpais** [comment]
I have exaclty the same issue as described by Andrio when using a Grails3 application though, which I'm not so sure if it's fully supported.

I really hope to be able to make this work, as it's the only proper plugin for API documentation I've found in the grails ecosystem.

Thank you Ajay. ;)

**Comment by ajay-kmr** [comment]
@aspich / @miguelpais ,

Please share the annotations used in your controller classes where you are trying to achieve this.
Also share the details of UrlMappings.groovy used for this controller.
Note:- the valid values for "paramType" attribute of @ApiImplicitParam annotation are {@code path}, {@code query}, {@code body}, {@code header} or {@code form}.

**Comment by aspich** [comment]
Hi, after a couple of more tests, it turns out the root cause is related to AspectJ. I am using for each controller method, along with the Api* swagger anotations, a proprietary annotation "@SecureCheck" which uses an AspectJ @Pointcut and @Around method for authorization.

If I remove my annotation, the documentation generates without any problem.  However, it seems that Swagger is unable to deal with the "@Around" aspect, somehow ending up to ignore all the "@ApiImplicitParam" annotations..

Maybe an issue for Swagger team?

Cheers

**Comment by ajay-kmr** [comment]
As described earlier, the root cause is related to AspectJ.
If required any help, please email your sample code explicitly.

So closing this issue.

THanks
