### ISSUE TITLE
Including this plugin stops logback logging from working in my application

### ISSUE THREAD

**Issue by davidbairdala** [ajay-kmr/swagger#4]
Steps to reproduce
1. Create new Grails 3 application
2. Create dummy service method with log.info messages
3. Configure logback.groovy so that log messages appear in the console (logger('grails.app', DEBUG)
4. Add dependency on Swagger plugin (1.0.0)
5. Re-run app - log messages do not appear

Any suggestions you might have would be greatly appreciated.

**Comment by ajay-kmr** [comment]
Hi,

This is an issue with swagger servlet jar.
Issue has already been raised for this:- [https://github.com/swagger-api/swagger-core/issues/1813](https://github.com/swagger-api/swagger-core/issues/1813)

However, you can easily overcome this issue by explicitly setting the name of your logback configuration file in your **build.gradle** using:-
```
bootRun {
    jvmArgs = [
            "-Dlogging.config=${project.projectDir}/grails-app/conf/logback.groovy"
    ]
}
```
Alternatively, you can also pass the name of logback configuration file using JVM argumants or system properties as follow:-
`java -Dlogback.configurationFile=/path/to/config.xml`

Please refer [this link](https://logback.qos.ch/manual/configuration.html#configFileProperty) to know more about how to set logback config file location.

Thanks.

**Comment by davidbairdala** [comment]
Thanks Ajay, I'll try the work around. 

Cheers, David.

**Comment by ajay-kmr** [comment]
Closing this issue as the solution to this problem is already mentioned in this thread and also in the documentation of this plugin.

**Comment by HardikModha** [comment]
@ajay-kmr The given suggestion in the README is not working for me. I'm using Grails v3.2.5. I fixed it by updating `swagger-servlet` dependency to `1.5.17`.
