### ISSUE TITLE
Issues when used in Grails 3.3.0

### ISSUE THREAD

**Issue by jfrosch** [ajay-kmr/swagger#5]
I added the swagger plugin to our Grails 3.3.0 project which uses Mongo DB. The integration tests started failing with these errors:
`Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.grails.datastore.mapping.mongo.MongoDatastore]: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: org/hibernate/validator/spi/resourceloading/ResourceBundleLocator
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:154)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:122)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:271)`
Since we're using Mongo, I was surprised to see these Hibernate-related errors. Am not really sure what's the issue, but I took a quick run at upgrading the swagger plugin to use Grails 3.3. I made the minimal changes to get the plugin to build, but the same issue occurred after I tried the 3.3 upgraded plugin. Am still investigating...

Note: I found that by adding Hibernate5 back into the dependencies, the issue went away; however, we don't want to pollute out dependencies with Hibernate. Also, doing so add further complications, like having to add special mapping configuration to each domain to get it to use Mongo.

**Comment by jfrosch** [comment]
I've finally been able to get back to this issue. I've tracked the Hibernate dependency down to core Grails and not the Swagger plugin. I'll work with the Grails Team to learn if the Hibernate dependency is required even when only using Mongo.

**Comment by bAmrish** [comment]
I am facing similar issue when I added swagger dependency. It seems to look for Hibernate validator. Adding `compile "org.hibernate:hibernate-validator"` seems to solve the issue.
